version: "3.8"
services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./www:/www
    ports:
      - 80:80
    links:
      - php_app

  php_app:
    build: config/php
    container_name: php_app
    volumes:
      - ./www:/www
    environment:
      - SESSION_HANDLER=redis
      - SESSION_PATH=tcp://redis:6379?auth=${REDIS_PASSWORD}
      - SESSION_MAX_TIME_LIFE=86400

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

  postgresql:
    image: postgres:15.2
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}

  mysql:
    image: mysql:5.7.24
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    links:
      - mysql

