version: "3.2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./www:/www
    ports:
      - 80:80
    links:
      - php_app
  php_app:
    build: www
    container_name: php_app
    volumes:
      - ./www:/www
    environment:
      - SESSION_HANDLER=redis
      - SESSION_PATH=tcp://redis:${REDIS_PORT}?auth=${REDIS_PASSWORD}
      - SESSION_MAX_TIME_LIFE=86400
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    links:
      - mysql

